# Generated by Django 5.1.2 on 2024-10-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=50)),
                ('testimonial_text', models.TextField()),
                ('stars', models.IntegerField(default=0)),
            ],
        ),
    ]
