# Generated by Django 5.1.2 on 2024-10-23 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=50)),
                ('testimonial_text', models.TextField()),
                ('stars', models.IntegerField(default=0)),
                ('client_image', models.ImageField(blank=True, null=True, upload_to='testimonial_clients_images/')),
            ],
        ),
    ]
