# Generated by Django 5.1.2 on 2024-10-30 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_active_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
