# Generated by Django 5.1.2 on 2024-10-20 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_stars_review_stars'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='weight',
            new_name='pack_weight',
        ),
    ]
