# Generated by Django 5.1.2 on 2024-10-20 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_detailed_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='review',
            field=models.ManyToManyField(blank=True, related_name='products', to='store.review'),
        ),
    ]
