# Generated by Django 5.1.2 on 2024-10-20 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_product_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stars_count',
            field=models.IntegerField(default=0),
        ),
    ]
